sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js: '8'
script: yarn build
before_install: scripts/travis/before_install.sh
install: 
    - yarn
    - yarn bootstrap
after_success: scripts/travis/after_success.sh
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
